process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';

require('../config/env');

const webpack = require('webpack');
const WebpackDevServer = require('webpack-dev-server');
const configFactory = require('../config/webpack.config');
const createDevServerConfig = require('../config/webpackDevServer.config');

const HOST = process.env.HOST;
const PORT = process.env.PORT;

const config = configFactory();
const compiler = webpack(config);

// Serve webpack assets generated by the compiler over a web server.
const serverConfig = createDevServerConfig(undefined, `${HOST}:${PORT}`);
const devServer = new WebpackDevServer(compiler, serverConfig);
devServer.listen(PORT, HOST, (err) => {
  if (err) {
    return console.log(err);
  }

  console.log('Starting the development server...');
});

['SIGINT', 'SIGTERM'].forEach((sig) => {
  process.on(sig, () => {
    devServer.close();
    process.exit();
  });
});
