name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: install dependencies
        run: |
          yarn install
        env:
          CI: true
      - name: Start server in the background
        run: |
          node ./src/utils/generate-stubs.js
          yarn run start-endpoints &
          timeout 60 bash -c 'until echo > /dev/tcp/localhost/5000; do sleep 2; done'
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          install: false
          browser: chrome
          headless: true
          start: yarn run start
          working-directory: src/tests
          wait-on: 'http://localhost:5000/playlists'
        env:
          NODE_ENV: test
          API_URL: 'http://localhost:5000'
          PUBLIC_URL: 'http://localhost:9000'
          HOST: 'localhost'
          PORT: 9000
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: videos
