name: Pact Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn install
    # - name: Run consumer tests
    #   run: |
    #     yarn run pact-c
    #     [[ -n $(git status -uno --porcelain) ]] && echo "consumers have changed contacts - failing CI. Please run consumer pact tests and commit" && kill -SIGINT $$
    #   env:
    #     ENV: CI
    - name: Start endpoint server
      run: |
        yarn run start-endpoints &
        timeout 60 bash -c 'until echo > /dev/tcp/localhost/5000; do sleep 2; done'
    - name: Run provider tests
      run: yarn run pact-p

